run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - revive
    - gci
    - gofumpt
    - whitespace
    - godot

issues:
  include:
    - EX0002 # disable excluding of issues about comments from golint
