logging:
  level: DEBUG
  developmentMode: false

server:
  port: 8079

mqtt:
  host: ":"
  port: 9641
  timeout: 3s

metrics:
  - mqtt_topic: "/home/+/memory"
    prom_name: "memory"
    type: "gauge"
    help: "free memory of a device"
    const_labels:
      - mylabel: "label value"
  - mqtt_topic: "/home/rpi/#"
    prom_name: "rpi"
    type: "gauge"
