name: dockerfile validator

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/dockerfile-validator.yml'

jobs:
  test:
    name: verify-dockerfile
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v5
    - name: Verify Dockerfile
      uses: ghe-actions/dockerfile-validator@v5
      with:
        dockerfile: 'Dockerfile'
        lint: 'dockerlint'
