name: build docker image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+' # Push events to matching v*, i.e. v1.0, v20.15

jobs:
  build:
    name: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          NEW_TAG=$(echo "${{ github.ref }}" | cut -d "/" -f3)
          echo "Docker image tag: ${NEW_TAG}"
          docker buildx build --push \
            --tag torilabs/mqtt-prometheus-exporter:latest \
            --tag torilabs/mqtt-prometheus-exporter:${NEW_TAG} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
